"""
Django settings for corp project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '95yclb=id18m4q92@7%@==g$9tbptjnbguqcc)z(lc^9l&l83='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '192.168.0.250',
    '127.0.0.1'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'bootstrapform',

    'complaints',
    'infinity',
    'smena',
    'salary',
    'corp_stats',
    'directory',
    'gibdd',
    'ats',
    'wash'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'corp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'corp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'Corp',
        'USER': 'hivee',
        'PASSWORD': 'q2w2e3r4t5',
        'HOST': '127.0.0.1',
        'PORT': '9000',
    },
    'Cx_TaxiConfiguration': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'Cx_TaxiConfiguration',
        'USER': 'cxdbuser',
        'PASSWORD': 'cxdbwizard',
        'HOST': '127.0.0.1',
        'PORT': '10000',
    },
    'Cx_TaxiActive': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'Cx_TaxiActive',
        'USER': 'cxdbuser',
        'PASSWORD': 'cxdbwizard',
        'HOST': '127.0.0.1',
        'PORT': '10000',
    },
    'Cx_TaxiStatistics': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'Cx_TaxiStatistics',
        'USER': 'cxdbuser',
        'PASSWORD': 'cxdbwizard',
        'HOST': '127.0.0.1',
        'PORT': '10000',
    },
    'fb': {
        'ENGINE': 'firebird',
        'NAME': 'C:\InfinityBase_T\INFDATA.DAT',   # Path to database or db alias
        'USER': 'INFINITYUSER',           # Your db user
        'PASSWORD': 'wizard',    # db user password
        'HOST': '127.0.0.1',        # Your host machine
        'PORT': '3050',             # If is empty, use default 3050
        'OPTIONS': {'charset': 'WIN1251'}
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)


# Настройка ПОЧТЫ для отправки уведомлений

EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'sky_auto_corp_not_for_use@taxirossiya.ru'
EMAIL_HOST_PASSWORD = 'rvuwvbrcgeszkcne'
DEFAULT_FROM_EMAIL = 'ТАКСИ РОССИЯ КОРП - Служебная Рассылка'
DEFAULT_TO_EMAIL = 'sky_auto_corp_not_for_use@taxirossiya.ru'
